### ISSUE TITLE
Fatal error on WP 5.6

### ISSUE THREAD

**Issue by antonyjsmith** [elightup/erocket#2]
Hi there, getting this error on a site updated to WP 5.6. Replicated on a clean install too.

Uncaught ArgumentCountError: Too few arguments to function render_block_core_social_link(), 1 passed in /wp-content/plugins/erocket/src/Sharing.php on line 175 and exactly 3 expected in /wp-includes/blocks/social-link.php:17
Stack trace:
#0 /wp-content/plugins/erocket/src/Sharing.php(175): render_block_core_social_link(Array)
#1 /wp-content/plugins/erocket/src/Sharing.php(144): ERocket\Sharing->get_html()
#2 /wp-includes/class-wp-hook.php(287): ERocket\Sharing->output(‘\n<p>This is a t…’)
#3 /wp-includes/plugin.php(212): WP_Hook->apply_filters(‘\n<p>This is a t…’, Array)

It would appear to be the addition of two new arguments in core, the diff is here:

https://github.com/WordPress/WordPress/commit/b667105f6010f77193144bee71067d5a53a7354c#diff-2d80df998948cc64bf2e6b1c4333c4f3051e40aa761335d7dce25b9f89e78025

**Comment by tuyenlq94** [comment]
Closed in 59f79b8
